const PremierImages=[
    {
        src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
        alt:"Zack",
        title:"Zack",
        subtitle:"English"
    },
    {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  },
  {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  },
  {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  },
  {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  },
  {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  },
  {
      src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00122511-myxaqdugrd-portrait.jpg",
      alt:"Zack",
      title:"Zack",
      subtitle:"English"
  }
];

export default PremierImages;